baseURL = "/"
languageCode = "zh-cn"
title = "Casey's Pixel Log"
theme = "digio-theme"
enableGitInfo = true

[build]
  writeStats = true

[[menu.main]]
  name = "首页"
  url = "/"
[[menu.main]]
  name = "文章"
  url = "/posts"